# Generated by Django 5.0.6 on 2024-09-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('action', models.TextField(max_length=500)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
