# Generated by Django 5.0.6 on 2024-09-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_useractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
